"""add_fcm_and_reminders

Revision ID: 6fd1b7f8d195
Revises: 775980ee75bc
Create Date: 2026-02-19 16:38:24.543064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd1b7f8d195'
down_revision: Union[str, Sequence[str], None] = '775980ee75bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('reminder_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('todos', sa.Column('notification_sent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('fcm_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    op.drop_column('todos', 'notification_sent')
    op.drop_column('todos', 'reminder_time')
    # ### end Alembic commands ###
